# Generated by Django 4.0.4 on 2022-04-28 09:08

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_time_in', models.DateTimeField(auto_now_add=True)),
                ('headline', models.CharField(max_length=128)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp_text', models.TextField()),
                ('resp_time_in', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('resp_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.ad')),
                ('resp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, unique=True)),
                ('authorUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.ad')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.category')),
            ],
        ),
        migrations.CreateModel(
            name='AdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.category')),
                ('ad_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.ad')),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyright', to='advert.author'),
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advert.category'),
        ),
    ]
